# Generated by Django 3.0.6 on 2021-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('current_balance', models.FloatField(default=0, max_length=10)),
            ],
        ),
    ]
