# Generated by Django 3.0.6 on 2021-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210310_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
