# Generated by Django 3.0.6 on 2021-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210310_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='transectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.IntegerField(max_length=30)),
                ('to_account', models.IntegerField(max_length=30)),
                ('amount', models.FloatField(default=0, max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
