# Generated by Django 3.0.6 on 2021-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210310_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transectionhistory',
            name='date_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
